language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jeyfarmer/react-test -f ./client/Dockerfile.dev ./client

script:
- docker run -e CI=true jeyfarmer/react-test npm test

after_success:
  - docker build -t jeyfarmer/multi-client ./client
  - docker build -t jeyfarmer/multi-nginx ./nginx
  - docker build -t jeyfarmer/multi-server ./server
  - docker build -t jeyfarmer/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images and push to docker hub
  - docker push jeyfarmer/multi-client
  - docker push jeyfarmer/multi-nginx
  - docker push jeyfarmer/multi-server
  - docker push jeyfarmer/multi-worker